// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// evaluate
Rcpp::RObject evaluate(Rcpp::Function fun, Rcpp::RObject data);
RcppExport SEXP thread_evaluate(SEXP funSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type fun(funSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluate(fun, data));
    return rcpp_result_gen;
END_RCPP
}
