# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init <- function() {
    invisible(.Call('thread_init', PACKAGE = 'thread'))
}

join_bg <- function() {
    invisible(.Call('thread_join_bg', PACKAGE = 'thread'))
}

store <- function(fun, data) {
    invisible(.Call('thread_store', PACKAGE = 'thread', fun, data))
}

trigger_evaluation <- function() {
    invisible(.Call('thread_trigger_evaluation', PACKAGE = 'thread'))
}

evaluation_result <- function() {
    .Call('thread_evaluation_result', PACKAGE = 'thread')
}

